### ISSUE TITLE
personFunctionType restriction

### ISSUE THREAD

**Issue by AFoletti** [blw-ofag-ufag/eCH-0261#11]
_personFunction-Code_ in _personFunctionType_ is an _xs:token_ with _xs:maxLength value="6"_
Is it intended to leave this element open to more or less anything up to 6 characters?
By looking at the documentation (PDF page 28) I am under the impression that:

1. we should limit this to digits
2. Actually, we should limit this to **6** digits, since higher hierarchical levels do not always make much sense in the context of this list (example: _0100 Andere (digiFLUX)_ may be OK, but _0201 Agrarsektordaten_ probably is not OK since is not really a role a person can have).

Number 2 would however need a refactoring of the list...

https://github.com/blw-ofag-ufag/eCH-0261/blob/77843b9bf5c415a735d5ad6c23ba4a1f1bc2b902/src/eCH-0261-1-0.xsd#L542

Open for discussion 😄

**Comment by lars-steffen** [comment]
it was decided to leave the number of digits open (1 - 50)

**Comment by lars-steffen** [comment]
fixed with #23
