### ISSUE TITLE
Tagging and branching conventions

### ISSUE THREAD

**Issue by AFoletti** [blw-ofag-ufag/eCH-0261#16]
I am referring here to [Steven's branch about naming conventions](https://github.com/blw-ofag-ufag/eCH-0261/tree/improvement/v1/branchingConventions) since we discussed but we just came to the conclusion that the branch will not be merged nor deleted, leaving the issue in kind of a limbo.

My goal with this issue is to open a discussion and eventually to achieve a decision resulting in an **action**.

My 2 cents:

- we all agreed upon the need of naming convention to keep some order. This makes in my opinion Steven's work in the referenced branch very much valuable and we should not discard it that easily.
- I am really convinced that the "tag" part of Steven's proposal  (up to [this line](https://github.com/blw-ofag-ufag/eCH-0261/blob/1e9bcc6892745e64735da79b9843b881d6d3d5e1/README.md?plain=1#L37)) is 100% spot on and should be merged/implemented. I would just add a requirement, for the "consultation" releases, to tick the "pre-release" box as in the picture
<img width="218" alt="image" src="https://github.com/blw-ofag-ufag/eCH-0261/assets/691243/01699cfb-ea5e-44b5-a639-837fc74b29b9">

- for the "work in progress" part, I would like to suggest to switch from _branching_ naming convention (which is rigid and honestly not very useful since you cannot filter for that) to work with a combination of Labels ("Feature", "Improvement" and "Fix" as suggested by Steven) and Milestones (referencing the projected release the change will be integrated into).
Moving this to Labels/Milestones will allow for a much more flexible management and the ability to filter issues and PR per change type and milestone, allowing for a better overview.

Up for discussion @hurni , @montanajava , @lars-steffen

**Comment by montanajava** [comment]
Issue still open: Need to adjust based on input from Ambrogio.

**Comment by AFoletti** [comment]
Solved with the new policy integrated into the readme
