### ISSUE TITLE
personWithFunctionType (reference to function)

### ISSUE THREAD

**Issue by lars-steffen** [blw-ofag-ufag/eCH-0261#21]
The personWithFunctionType contains a personIdentifier and a personFunction. Currently, the personFunction is of the data type personFunctionType. 
personFunctionType contains a code (xs:token, maxLength=50) and optionally a descriptor. 

--> Is it OK that personWithFunctionType contains an element "personFunctionType" or should it rather reference only the code, i.e. an xs:token (maxLength=50)?

**Comment by AFoletti** [comment]
_personFunctionType_ is to my understanding an external codelist.
This makes in my opinion the integration of the whole element instead of just a code actually wrong.

See https://github.com/blw-ofag-ufag/eCH-0261/issues/11 for another open discussion on the same list.

**Comment by lars-steffen** [comment]
fixed with #22
